language: go
go:
  - 1.11.x
  - 1.12.x

notifications:
  email: false

install:
  - export GO111MODULE=on
  - go mod download

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS gin DEFAULT CHARACTER SET utf8mb4;'
