language: go
go:
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - 1.17.x
  - 1.18.x
  - 1.19.x

notifications:
  email: false

install:
  - export config=../config.yml
  - go mod download

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS gin DEFAULT CHARACTER SET utf8mb4;'
